service: connectfour

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  memorySize: 1536
  timeout: 20

package:
  exclude:
    - .idea/**
    - layer-*/**
    - venv/**
    - dnn*/**
    - dqn/**
    - connect-four.iml
    - mcts*.txt
    - '*.ipynb'
    - valuenetwork/**


functions:
  start:
    handler: index.handler
    layers:
    - arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python36-SciPy1x:2
    events:
    - http:
        path: play/{action}
        method: get
        cors: true
