service: connectfour

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
- serverless-s3-sync

custom:
  siteName: playboardgames
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: d3

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: connectfour.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
            - s3:GetObject
            Resource:
              Fn::Join: [
                "", [
                "arn:aws:s3:::",
                {
                  "Ref": "StaticSite"
                },
                "/*"
              ]
              ]

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  memorySize: 3000
  timeout: 20
  iamRoleStatements: # permissions for all of your functions can be set here
  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-west-1:*:*"

package:
  exclude:
    - .idea/**
    - layer-*/**
    - venv/**
    - dnn*/**
    - dqn/**
    - connect-four.iml
    - mcts*.txt
    - '*.ipynb'
    - valuenetwork/**


functions:
  start:
    handler: index.handler
    layers:
    - arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python36-SciPy1x:2
    events:
    - http:
        path: play/{action}
        method: get
        cors: true

