service: connectfour

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  memorySize: 1536
  timeout: 20
  iamRoleStatements: # permissions for all of your functions can be set here
  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-west-1:*:*"

package:
  exclude:
    - .idea/**
    - layer-*/**
    - venv/**
    - dnn*/**
    - dqn/**
    - connect-four.iml
    - mcts*.txt
    - '*.ipynb'
    - valuenetwork/**


functions:
  start:
    handler: index.handler
    layers:
    - arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python36-SciPy1x:2
    events:
    - http:
        path: play/{action}
        method: get
        cors: true
